[package]
name = "chiyocore-firmware"
version = "0.1.0"
edition = "2024"
rust-version = "1.93"

[[bin]]
name = "chiyocore"
path = "./src/main.rs"

[dependencies]
ed25519-compact = { version = "2.2.0", default-features = false }
embassy-executor = { version = "0.10", features = ["defmt"] }
esp-bootloader-esp-idf = { git = "https://github.com/esp-rs/esp-hal.git", rev = "91c776f5c95ac7c3027d12569e2cfdebacfefc73",  features = ["esp32s3"] }
heapless = { version = "0.9.2", features = ["alloc", "serde"] }
litemap = "0.8.1"
littlefs2 = { git = "https://github.com/kore-signet/littlefs2.git", features = ["alloc", "c-stubs"] }
rand = { version = "0.9", default-features = false }
smol_str = { version = "0.3.6", default-features = false, features = ["serde"] }
defmt = { version = "1.0.1", features = ["alloc"] }
esp-rtos = { git = "https://github.com/esp-rs/esp-hal.git", rev = "91c776f5c95ac7c3027d12569e2cfdebacfefc73",  features = ["esp32s3", "esp-alloc", "esp-radio", "defmt", "alloc"] }
esp-alloc = { git = "https://github.com/esp-rs/esp-hal.git", rev = "91c776f5c95ac7c3027d12569e2cfdebacfefc73", features = ["esp32s3", "nightly"] }
esp-hal = { git = "https://github.com/esp-rs/esp-hal.git", rev = "91c776f5c95ac7c3027d12569e2cfdebacfefc73", features = ["esp32s3", "defmt", "psram", "unstable"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"
incremental = true

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false

[profile.dev.package.esp-radio]
opt-level = 3

[profile.dev.package.esp-hal]
opt-level = 3

[profile.dev.package.esp-storage]
opt-level = 3

[profile.dev.package.esp-sync]
opt-level = 3

[profile.dev.package.esp-rtos]
opt-level = 3

[profile.dev.package.esp-bootloader-esp-idf]
opt-level = 3

[profile.dev.package.esp-alloc]
opt-level = 3

[profile.dev.package.esp-backtrace]
opt-level = 3

[profile.dev.package.esp-println]
opt-level = 3

[profile.dev.package.p384]
opt-level = 3
debug = false

[profile.dev.package.mbedtls-rs]
opt-level = 3

[patch.crates-io]
esp-hal = { git = "https://github.com/esp-rs/esp-hal.git", rev = "91c776f5c95ac7c3027d12569e2cfdebacfefc73"  }
edge-nal = { git = "https://github.com/sysgrok/edge-net.git" }