[firmware]
stack_size = 32768

[chiyocore]
config = { "wifi.pw" = "nya", "wifi.ssid" = "nya" }
default_channels = ["#test", "#emitestcorner"]

[stackup.chiyo0]
id = "chiyo0"

[stackup.chiyo0.layers.companion-0]
type = "chiyocore_companion::companionv2::Companion"
id = "chiyocompanion0"
tcp_port = 5000

[stackup.chiyo0.layers.ping_bot]
type = "chiyocore::ping_bot::PingBot"
name = "cafe / chiyobot 🌃☕"
channels = ["#test", "#emitestcorner"]

[stackup.chiyo0.layers.ttc_bot]
deps = { chiyocore-ttc = { git = "https://codeberg.org/emisignet/chiyocore-ttc.git" } }
type = "chiyocore_ttc::TTCBot"